language: php

php:
  - 5.3
  - 5.4

before_script:
    - mv /Tests/app/config/parameters.yml.dist /Tests/app/config/parameters.yml
    - mysql -e 'create database archivemytweets-test;'
    - composer self-update
    - composer install --dev --prefer-source

script: phpunit --coverage-text
